[workspace]
members = [
  "tools/factory-validator",
  "sdk/bex-media-url-resolver",
  "sdk/bex-media-url-resolver-v2",
  "plugins/direct-url",
  "plugins/instagram",
  "plugins/bandcamp",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.94"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
